os: osx
language: c

matrix:
  include:
    - osx_image: xcode8
    - osx_image: xcode10.1

env:
  global:
    - HOMEBREW_NO_ANALYTICS=1
    - HOMEBREW_NO_AUTO_UPDATE=1
    - MACOS=1

before_install:
  - curl -fsSOL https://raw.githubusercontent.com/Homebrew/install/6f9b04355b11f6849fed761725a1f10cb326e979/uninstall
  - sudo ruby uninstall --force
  - rm uninstall
  - hash -r

before_script:
  - git config --global protocol.version 1
  - echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/autobrew/install/master/install)"
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - brew help # trigger vendored ruby installation
#  - brew install v8 # just to test we are using autobrew bottles

script:
  - echo "Building commit range $TRAVIS_COMMIT_RANGE"
  - brew test-bot --local --skip-setup --skip-homebrew
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./upload_bottles.sh; fi'
